---
title: "Compile Tree by Site Series Info"
author: "Kiri Daust/Will MacKenzie"
date: "04/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
require(dplyr)
require(ggplot2)
require(MASS)
require(magrittr)
require(foreach)
require(reshape2)
require(reticulate)
require(Rcpp)
library(gridExtra)
library(data.table)
library(scales)
library(tidyr)
library(magrittr)
library(ggthemes)
library(flextable)
require(rgdal)
require(tmap)
library(sf)
```

Load data

```{r load data sets}
##Set drive with cloud data
if(dir.exists("C:/users/whmacken/Sync")){
  cloud_dir <- "C:/users/whmacken/Sync/CCISS_data/CommonTables/"
}else{
  cloud_dir <- "C:/Users/kirid/Sync/CCISS_data/CommonTables/"
}

###Read in data
## 1. All BGCS (info table from USA_BGC project)
bgc <- fread(paste0(cloud_dir,"All_BGCs_v11_21.csv"))
bgc_small <- bgc[,.(Source,Zone,BGC = Map_Label)]

## 2. All Site Series (info table from from USA_BGC project)
ss <- fread(paste0(cloud_dir, "WNA_SSeries_v11.csv"))
ss_small <- ss[,.(BGC, SS_NoSpace)]

## 3. All Edatopic (info table from USA_BGC project)
eda <- fread(paste0(cloud_dir, "Edatopic_v11_20.csv"))
eda_small <- eda[,.(SS_NoSpace,Edatopic,Special,Codes)]

## 4. All aSMR (modelled in aSMR_X_rSMR project)
asmr <- fread(paste0(cloud_dir, "modelled_WNAv11_rSMR_aSMR_grid_HalfStep.csv"))

## 5. All Feasibility (in part modelled in TreeSuitabilityPrediction project)
feasible <- fread(paste0(cloud_dir, "Feasibility_v11_21.csv"))
feas_small <- feasible[,.(SS_NoSpace, Spp, Feasible)]

## 6. All Site Index (modelled in SIBEC_Modelled project)
sibec <- fread(paste0(cloud_dir, "PredSI_May2020.csv"))
  
```
   
Combine and show missing

```{r combine}
any(duplicated(bgc_small))
any(duplicated(ss_small))
ss_small[, fD := .N > 1, by = key(ss_small)]
ss_small[(fD)]
any(duplicated(sibec))
sibec[,fD := .N > 1, by = key(sibec)]
sibec[(fD)]
any(duplicated(feas_small))
any(duplicated(eda_small))

ss_small <- unique(ss_small)
sibec <- unique(sibec)
feas_small <- unique(feas_small)
eda_small <- unique(eda_small)

setkey(bgc_small,BGC)
setkey(ss_small,BGC,SS_NoSpace)
bgc_ss <- merge(bgc_small, ss_small, all = T)
bgc_NoSS <- bgc_ss[is.na(BGC),SS_NoSpace]
ss_NoBGC <- bgc_ss[is.na(SS_NoSpace),BGC]

setkey(feas_small, SS_NoSpace, Spp)
ss_feas <- merge(ss_small, feas_small, by = "SS_NoSpace", all = T)
ss_NoFeas <- ss_feas[is.na(Spp),SS_NoSpace]
feas_NoSS <- ss_feas[is.na(BGC),SS_NoSpace]

setkey(sibec, SS_NoSpace, Spp)
ss_feas_sibec <- merge(ss_feas, sibec, by = c("SS_NoSpace","Spp"), all = T)
sibec_missingSpp <- ss_feas_sibec[,all(is.na(SIPred)), by = Spp][(V1),Spp]
sibec_missingSS <- ss_feas_sibec[,all(is.na(SIPred)), by = SS_NoSpace][(V1),SS_NoSpace]
temp <- ss_feas_sibec[(!Spp %in% sibec_missingSpp) & (!SS_NoSpace %in% sibec_missingSS),]

setkey(eda_small,SS_NoSpace)
ss_eda <- merge(ss_small, eda_small, all = T)


```

